### ISSUE TITLE
Remove host-only profile 

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/netmodules-plugin#62]
Calico always allow communication between a task and its host. We add a profile specifically for this communication in calico_mesos, but it is unnecessary as that functionality is already baked in. Remove the creation of this profile

**Comment by djosborne** [comment]
Actually, I believe that this issue isn't as straightforward as it seems. Many custom frameworks have special calls in their executors to send messages from a Task to the Mesos-master. I believe that the purpose of the host-only profile was misconstrued from this. Though calico default allows communication between an agent and its tasks, the `default_*` profiles should actually contain rules to allow a task to communicate with the mesos master.
